"use client";
import { Center } from "@/types/academic/center.interface";
import { ArchiveRecord } from "@/types/academic/archive.interface";
import { BulkUploadArchiveRequest } from "@/types/requests/archive.interface";
import { archiveRecordSchema } from "@/validations/academic/archive.validation";
import * as XLSX from "xlsx";
import { X, Upload, AlertCircle, ChevronDown } from "lucide-react";
import React, { useState, useRef, useEffect } from "react";
import { useIsAdmin } from "@/hooks/useIsAdmin";

interface ArchiveUploadModalProps {
  isOpen: boolean;
  onClose: () => void;
  onSave: (data: BulkUploadArchiveRequest) => void;
  centers: Center[];
  isUploading?: boolean; // Add upload state prop
}

const ArchiveUploadModal: React.FC<ArchiveUploadModalProps> = ({
  isOpen,
  onClose,
  onSave,
  centers,
  isUploading = false,
}) => {
  const { isAdmin } = useIsAdmin();
  const fileInputRef = useRef<HTMLInputElement>(null);
  const [selectedCenterId, setSelectedCenterId] = useState<string>("");
  const [selectedFile, setSelectedFile] = useState<File | null>(null);
  const [parsedData, setParsedData] = useState<ArchiveRecord[]>([]);
  const [validationErrors, setValidationErrors] = useState<
    Array<{ row: number; errors: string[] }>
  >([]);
  const [isProcessing, setIsProcessing] = useState(false);
  const [previewRows, setPreviewRows] = useState(10);
  const [duplicateRecords, setDuplicateRecords] = useState<Array<{ row: number; oldStudentId: string }>>([]);

  // Reset state when modal closes
  useEffect(() => {
    if (!isOpen) {
      handleReset();
    }
  }, [isOpen]);

  /**
   * Check if a string matches TT format: TT-XX-XXXXX
   */
  const isTTFormat = (id: string): boolean => {
    if (!id || typeof id !== "string") return false;
    const ttFormatRegex = /^TT-[A-Z]{2}-\d{5}$/;
    return ttFormatRegex.test(id.trim());
  };

  /**
   * NOTE: Backend generates student IDs automatically.
   * - oldStudentId: Preserved exactly from Excel if provided (used for record tallying).
   *   Backend only generates if empty/missing.
   * - newStudentId: Always generated by backend (never sent from frontend).
   * 
   * CRITICAL: oldStudentId must NEVER be regenerated if provided - it's used to match/tally legacy records.
   */

  /**
   * Format date from Excel - handles multiple formats:
   * - "2011-08-22" (YYYY-MM-DD string)
   * - Excel serial numbers
   * - Other date formats
   */
  const formatDateForArchive = (dateValue: any): string => {
    if (!dateValue) return "";

    // Handle Excel date serial numbers
    if (typeof dateValue === "number") {
      const excelEpoch = new Date(1899, 11, 30);
      const date = new Date(excelEpoch.getTime() + dateValue * 86400000);
      return date.toISOString().split("T")[0];
    }

    // Handle string dates
    if (typeof dateValue === "string") {
      const trimmed = dateValue.trim();

      // Handle YYYY-MM-DD format (e.g., "2011-08-22")
      if (/^\d{4}-\d{2}-\d{2}$/.test(trimmed)) {
        // Validate the date
        const date = new Date(trimmed);
        if (!isNaN(date.getTime())) {
          return trimmed; // Return as-is if valid
        }
      }

      // Handle other date formats
      const date = new Date(trimmed);
      if (!isNaN(date.getTime())) {
        return date.toISOString().split("T")[0];
      }

      // Try parsing as Excel date string (e.g., "8/22/2011")
      const excelDate = new Date(trimmed);
      if (!isNaN(excelDate.getTime())) {
        return excelDate.toISOString().split("T")[0];
      }
    }

    return "";
  };

  const handleFileSelect = async (event: React.ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0];
    if (!file) return;

    // Require center selection before file upload
    if (!selectedCenterId) {
      alert("Please select a center first before uploading a file.");
      if (fileInputRef.current) {
        fileInputRef.current.value = "";
      }
      return;
    }

    setSelectedFile(file);
    setIsProcessing(true);
    setValidationErrors([]);
    setParsedData([]);

    try {
      const data = await readExcelFile(file);
      setParsedData(data);

      // Validate data with centerId assigned
      const errors: Array<{ row: number; errors: string[] }> = [];
      data.forEach((record, index) => {
        try {
          // Ensure centerId is set before validation
          const recordWithCenter = {
            ...record,
            centerId: selectedCenterId,
          };
          archiveRecordSchema.validateSync(recordWithCenter, { abortEarly: false });
        } catch (error: any) {
          errors.push({
            row: index + 1,
            errors: error.errors || [error.message],
          });
        }
      });
      setValidationErrors(errors);

      // Detect duplicates based on oldStudentId
      const duplicates: Array<{ row: number; oldStudentId: string }> = [];
      const seenIds = new Map<string, number>(); // oldStudentId -> first row number
      
      data.forEach((record, index) => {
        const rowNum = index + 1;
        if (record.oldStudentId) {
          if (seenIds.has(record.oldStudentId)) {
            // This is a duplicate
            duplicates.push({
              row: rowNum,
              oldStudentId: record.oldStudentId,
            });
          } else {
            // First occurrence
            seenIds.set(record.oldStudentId, rowNum);
          }
        }
      });
      
      setDuplicateRecords(duplicates);
    } catch (error: any) {
      console.error("Failed to parse file:", error);
      alert(`Failed to parse file: ${error.message}`);
    } finally {
      setIsProcessing(false);
    }
  };

  const readExcelFile = (file: File): Promise<ArchiveRecord[]> => {
    return new Promise((resolve, reject) => {
      const reader = new FileReader();

      reader.onload = (e) => {
        try {
          const data = e.target?.result;
          const workbook = XLSX.read(data, { type: "binary" });
          const sheetName = workbook.SheetNames[0];
          const worksheet = workbook.Sheets[sheetName];
          const jsonData = XLSX.utils.sheet_to_json(worksheet);

          // Map Excel columns to ArchiveRecord fields
          const mappedData: ArchiveRecord[] = jsonData.map((row: any, index: number) => {
            // Try to map common column name variations
            const mapField = (excelName: string, variations: string[]) => {
              const lowerRow = Object.keys(row).reduce((acc, key) => {
                acc[key.toLowerCase().trim()] = row[key];
                return acc;
              }, {} as any);

              for (const variation of variations) {
                const lowerVar = variation.toLowerCase().trim();
                const value = lowerRow[lowerVar];
                if (value !== undefined && value !== null && value !== "") {
                  // Handle both string and numeric values
                  if (typeof value === "number") {
                    return String(value);
                  }
                  return String(value).trim(); // Convert to string and trim
                }
              }
              return null;
            };

            // Helper function to parse numeric values (handles currency, commas, etc.)
            const parseNumericField = (variations: string[]): number => {
              // Create lowercase row mapping for field lookup
              const lowerRow = Object.keys(row).reduce((acc, key) => {
                acc[key.toLowerCase().trim()] = row[key];
                return acc;
              }, {} as any);

              // Find the field value
              let rawValue: any = null;
              for (const variation of variations) {
                const lowerVar = variation.toLowerCase().trim();
                const value = lowerRow[lowerVar];
                if (value !== undefined && value !== null && value !== "") {
                  rawValue = value;
                  break;
                }
              }

              if (rawValue === null || rawValue === undefined || rawValue === "") {
                return 0;
              }

              // Handle numeric values directly from Excel
              if (typeof rawValue === "number") {
                return isNaN(rawValue) ? 0 : rawValue;
              }

              // Remove currency symbols, commas, and whitespace from string values
              const cleaned = String(rawValue)
                .replace(/[₦$€£¥,\s]/g, "")
                .trim();

              const parsed = parseFloat(cleaned);
              return isNaN(parsed) ? 0 : parsed;
            };

            const fullname = mapField("fullname", ["fullname", "full name", "name", "student name"]) || "";
            
            // CRITICAL: Preserve oldStudentId exactly from Excel - used for record tallying
            // Backend will only generate oldStudentId if it's empty/missing
            // Do NOT generate any IDs on frontend
            const oldStudentId = mapField("oldStudentId", [
              "oldstudentid",
              "old student id",
              "student old id",
              "old_student_id",
              "student id",
              "studentid",
            ]) || ""; // Preserve exactly as in Excel, or "" if not provided
            
            // Backend always generates newStudentId - never send from frontend
            const newStudentId: string | null = null;

            return {
              centerId: selectedCenterId, // Use selected center
              userOldId: mapField("userOldId", ["useroldid", "user old id", "old user id", "user_old_id"]) || oldStudentId, // Use oldStudentId as fallback
              userNewId: mapField("userNewId", ["usernewid", "user new id", "new user id", "user_new_id"]) || null,
              fullname: fullname,
              email: mapField("email", ["email", "e-mail"]) || "",
              phone: mapField("phone", ["phone", "phone number", "mobile", "contact"]) || "",
              courseEnrolled: mapField("courseEnrolled", ["courseenrolled", "course enrolled", "course", "course name"]) || "",
              coursePrice: parseNumericField(["courseprice", "course price", "price", "fee", "courseprice", "course_price"]),
              enrollmentDate: formatDateForArchive(mapField("enrollmentDate", ["enrollmentdate", "enrollment date", "enrolled date", "enroll_date", "enrollment_date"]) || ""),
              birthDate: formatDateForArchive(mapField("birthDate", ["birthdate", "birth date", "dob", "date of birth", "birth_date"]) || ""),
              oldStudentId: oldStudentId, // Preserved exactly from Excel, or "" if not provided (backend generates)
              newStudentId: newStudentId, // Always null - backend generates
              totalPayment: parseNumericField(["totalpayment", "total payment", "paid", "amount paid", "total_payment", "totalpaid", "amountpaid", "total paid"]),
              pendingPayment: parseNumericField(["pendingpayment", "pending payment", "balance", "outstanding", "pending_payment", "pendingbalance", "outstanding balance"]),
              status: mapField("status", ["status", "student status"]) || "archived",
              source: (mapField("source", ["source", "archive source"]) || "legacy_erp") as "legacy_erp" | "graduated",
            };
          });

          resolve(mappedData);
        } catch (error: any) {
          reject(new Error(`Failed to parse Excel file: ${error.message}`));
        }
      };

      reader.onerror = () => reject(new Error("Failed to read file"));
      reader.readAsBinaryString(file);
    });
  };

  const handleUpload = () => {
    // Prevent double-click/duplicate uploads
    if (isUploading) {
      return;
    }

    if (!selectedCenterId) {
      alert("Please select a center");
      return;
    }

    if (parsedData.length === 0) {
      alert("No data to upload. Please select a file first.");
      return;
    }

    // Assign centerId to all records (override any centerId from file)
    const recordsWithCenter = parsedData.map((record) => ({
      ...record,
      centerId: selectedCenterId, // Always use selected center
    }));

    // Filter out records with validation errors AND duplicates
    // Keep only the first occurrence of each oldStudentId
    const seenIds = new Set<string>();
    const validRecords = recordsWithCenter.filter((record, index) => {
      const rowNum = index + 1;
      
      // Skip if has validation errors
      if (validationErrors.some((error) => error.row === rowNum)) {
        return false;
      }
      
      // Skip if duplicate (keep first occurrence only)
      if (record.oldStudentId && seenIds.has(record.oldStudentId)) {
        return false;
      }
      
      // Mark as seen
      if (record.oldStudentId) {
        seenIds.add(record.oldStudentId);
      }
      
      return true;
    });

    if (validRecords.length === 0) {
      alert("No valid records to upload. Please fix the errors in your file.");
      return;
    }

    // Show warning if duplicates were found
    if (duplicateRecords.length > 0) {
      const duplicateCount = duplicateRecords.length;
      const duplicateIds = duplicateRecords.map(d => d.oldStudentId).join(", ");
      console.warn(`Found ${duplicateCount} duplicate record(s). Duplicates will be ignored.`, duplicateIds);
    }

    onSave({ records: validRecords });
  };

  const handleReset = () => {
    setSelectedFile(null);
    setParsedData([]);
    setValidationErrors([]);
    setDuplicateRecords([]);
    setSelectedCenterId("");
    if (fileInputRef.current) {
      fileInputRef.current.value = "";
    }
  };

  if (!isOpen) return null;

  const validRecordsCount = parsedData.length - validationErrors.length;
  const errorRecordsCount = validationErrors.length;
  const canUpload = selectedCenterId && parsedData.length > 0 && validRecordsCount > 0;

  return (
    <div className="fixed inset-0 bg-black bg-opacity-65 flex items-center justify-center z-50 p-4 font-sans">
      <div className="relative bg-white p-6 rounded-2xl shadow-xl w-full max-w-4xl max-h-[95vh] overflow-hidden flex flex-col">
        {/* Header */}
        <div className="flex justify-between items-center pb-4 border-b border-gray-200">
          <h2 className="text-xl font-bold text-gray-800">Upload Archive Records</h2>
          <button
            onClick={onClose}
            className="p-2 rounded-full bg-gray-100 text-gray-500 hover:bg-gray-200 transition-colors"
            aria-label="Close modal"
          >
            <X size={20} />
          </button>
        </div>

        {/* Modal Content - Scrollable */}
        <div className="mt-6 flex flex-col h-full overflow-y-auto pr-2 custom-scroll">
          {/* Center Selection */}
          <div className="mb-6">
            <label className="block text-sm font-medium text-gray-700 mb-2">
              Select Center *
            </label>
            <div className="relative">
              <select
                value={selectedCenterId}
                onChange={(e) => {
                  setSelectedCenterId(e.target.value);
                  // Reset file selection when center changes
                  if (selectedFile) {
                    handleReset();
                  }
                }}
                className="w-full h-10 px-3 text-sm text-gray-600 rounded-lg bg-gray-100 border-2 border-transparent focus:border-blue-500 focus:outline-none transition-colors appearance-none"
                disabled={!isAdmin}
              >
                <option value="">Select Center</option>
                {centers.map((center) => (
                  <option key={center.id} value={center.id}>
                    {center.name}
                  </option>
                ))}
              </select>
              <span className="absolute right-3 top-2/3 -translate-y-1/2 text-gray-400 pointer-events-none">
                <ChevronDown size={18} />
              </span>
            </div>
            {!selectedCenterId && (
              <p className="text-xs text-red-500 mt-1">Please select a center before uploading a file</p>
            )}
          </div>

          {/* File Upload */}
          <div className="mb-6">
            <label className="block text-sm font-medium text-gray-700 mb-2">
              Upload Excel/CSV File *
            </label>
            <div className="flex items-center gap-4">
              <input
                ref={fileInputRef}
                type="file"
                accept=".xlsx,.xls,.csv"
                onChange={handleFileSelect}
                className="hidden"
                id="archive-file-input"
                disabled={!selectedCenterId}
              />
              <label
                htmlFor="archive-file-input"
                className={`flex items-center gap-2 px-4 py-2 rounded-md cursor-pointer transition-colors ${
                  selectedCenterId
                    ? "bg-blue-600 text-white hover:bg-blue-700"
                    : "bg-gray-300 text-gray-500 cursor-not-allowed"
                }`}
              >
                <Upload size={18} />
                Choose File
              </label>
              {selectedFile && (
                <span className="text-sm text-gray-600">{selectedFile.name}</span>
              )}
            </div>
            <p className="text-xs text-gray-500 mt-2">
              Supported formats: Excel (.xlsx, .xls) or CSV
            </p>
          </div>

          {/* Processing Indicator */}
          {isProcessing && (
            <div className="mb-4 p-4 bg-blue-50 rounded-md">
              <p className="text-sm text-blue-700">Processing file...</p>
            </div>
          )}

          {/* Summary */}
          {parsedData.length > 0 && (
            <div className="mb-6 p-4 bg-gray-50 rounded-md">
              <div className="flex items-center justify-between mb-2">
                <h3 className="font-semibold text-gray-800">Upload Summary</h3>
                <div className="flex gap-4 text-sm">
                  <span className="text-green-600">
                    Valid: {validRecordsCount} record(s)
                  </span>
                  {errorRecordsCount > 0 && (
                    <span className="text-red-600">
                      Errors: {errorRecordsCount} record(s)
                    </span>
                  )}
                  {duplicateRecords.length > 0 && (
                    <span className="text-amber-600">
                      Duplicates: {duplicateRecords.length} record(s)
                    </span>
                  )}
                </div>
              </div>
              <p className="text-sm text-gray-600">
                Center: {centers.find((c) => c.id === selectedCenterId)?.name || "Not selected"}
              </p>
            </div>
          )}

          {/* Duplicate Records Warning */}
          {duplicateRecords.length > 0 && (
            <div className="mb-6 p-4 bg-amber-50 rounded-md border border-amber-200">
              <div className="flex items-center gap-2 mb-2">
                <AlertCircle className="text-amber-600" size={18} />
                <h3 className="font-semibold text-amber-800">
                  Duplicate Records Found ({duplicateRecords.length} row(s))
                </h3>
              </div>
              <p className="text-sm text-amber-700 mb-2">
                The following records have duplicate Student IDs. Only the first occurrence will be uploaded:
              </p>
              <div className="max-h-40 overflow-y-auto">
                {duplicateRecords.slice(0, 10).map((dup, index) => (
                  <div key={index} className="text-sm text-amber-700 mb-1">
                    Row {dup.row}: Student ID "{dup.oldStudentId}" (duplicate - will be ignored)
                  </div>
                ))}
                {duplicateRecords.length > 10 && (
                  <p className="text-sm text-amber-600 mt-2">
                    ... and {duplicateRecords.length - 10} more duplicate(s)
                  </p>
                )}
              </div>
            </div>
          )}

          {/* Validation Errors */}
          {validationErrors.length > 0 && (
            <div className="mb-6 p-4 bg-red-50 rounded-md border border-red-200">
              <div className="flex items-center gap-2 mb-2">
                <AlertCircle className="text-red-600" size={18} />
                <h3 className="font-semibold text-red-800">
                  Validation Errors ({validationErrors.length} row(s))
                </h3>
              </div>
              <div className="max-h-40 overflow-y-auto">
                {validationErrors.slice(0, 10).map((error, index) => (
                  <div key={index} className="text-sm text-red-700 mb-1">
                    Row {error.row}: {error.errors.join(", ")}
                  </div>
                ))}
                {validationErrors.length > 10 && (
                  <p className="text-sm text-red-600 mt-2">
                    ... and {validationErrors.length - 10} more error(s)
                  </p>
                )}
              </div>
            </div>
          )}

          {/* Preview Table */}
          {parsedData.length > 0 && (
            <div className="mb-6">
              <div className="flex items-center justify-between mb-3">
                <h3 className="font-semibold text-gray-800">
                  Preview (First {Math.min(previewRows, parsedData.length)} rows)
                </h3>
                <select
                  value={previewRows}
                  onChange={(e) => setPreviewRows(Number(e.target.value))}
                  className="text-sm px-2 py-1 border rounded"
                >
                  <option value={10}>10 rows</option>
                  <option value={20}>20 rows</option>
                  <option value={50}>50 rows</option>
                </select>
              </div>
              <div className="overflow-x-auto max-h-96 border rounded">
                <table className="min-w-full text-sm">
                  <thead className="bg-gray-100 sticky top-0">
                    <tr>
                      <th className="p-2 text-left border">Actions</th>
                      <th className="p-2 text-left border">Student ID (New)</th>
                      <th className="p-2 text-left border">Old Student ID (Legacy)</th>
                      <th className="p-2 text-left border">Full Name</th>
                      <th className="p-2 text-left border">Email</th>
                      <th className="p-2 text-left border">Phone</th>
                      <th className="p-2 text-left border">Course</th>
                      <th className="p-2 text-left border">Status</th>
                    </tr>
                  </thead>
                  <tbody>
                    {parsedData.slice(0, previewRows).map((record, index) => {
                      const rowNum = index + 1;
                      const hasError = validationErrors.some((e) => e.row === rowNum);
                      const isDuplicate = duplicateRecords.some((d) => d.row === rowNum);
                      return (
                        <tr
                          key={index}
                          className={`${
                            hasError
                              ? "bg-red-50"
                              : isDuplicate
                              ? "bg-amber-50"
                              : ""
                          }`}
                        >
                          <td className="p-2 border">
                            <button
                              onClick={() => {
                                const newData = parsedData.filter((_, i) => i !== index);
                                setParsedData(newData);
                                // Re-validate after removal (adjust row numbers)
                                const newErrors = validationErrors
                                  .filter((e) => e.row !== rowNum)
                                  .map((e) => ({
                                    ...e,
                                    row: e.row > rowNum ? e.row - 1 : e.row,
                                  }));
                                setValidationErrors(newErrors);
                                // Re-check duplicates (adjust row numbers)
                                const newDuplicates = duplicateRecords
                                  .filter((d) => d.row !== rowNum)
                                  .map((d) => ({
                                    ...d,
                                    row: d.row > rowNum ? d.row - 1 : d.row,
                                  }));
                                setDuplicateRecords(newDuplicates);
                              }}
                              className="text-red-600 hover:text-red-800 hover:bg-red-100 px-2 py-1 rounded transition-colors"
                              title="Remove this record"
                            >
                              <X size={16} />
                            </button>
                          </td>
                          <td className="p-2 border">
                            {record.newStudentId || (record.oldStudentId ? record.oldStudentId : "Will be generated")}
                            {isDuplicate && (
                              <span className="ml-2 text-xs text-amber-600">(Duplicate)</span>
                            )}
                          </td>
                          <td className="p-2 border">{record.oldStudentId || "Will be generated"}</td>
                          <td className="p-2 border">{record.fullname}</td>
                          <td className="p-2 border">{record.email}</td>
                          <td className="p-2 border">{record.phone}</td>
                          <td className="p-2 border">{record.courseEnrolled}</td>
                          <td className="p-2 border">{record.status}</td>
                        </tr>
                      );
                    })}
                  </tbody>
                </table>
              </div>
            </div>
          )}
        </div>

        {/* Footer - Sticky */}
        <div className="flex justify-end gap-3 mt-6 pt-6 border-t border-gray-200 sticky bottom-0 bg-white">
          <button
            type="button"
            onClick={() => {
              if (!isUploading) {
                handleReset();
                onClose();
              }
            }}
            disabled={isUploading}
            className={`px-6 py-2 text-gray-700 bg-gray-200 rounded-md transition-colors ${
              isUploading
                ? "opacity-50 cursor-not-allowed"
                : "hover:bg-gray-300"
            }`}
          >
            Cancel
          </button>
          {parsedData.length > 0 && !isUploading && (
            <button
              type="button"
              onClick={handleReset}
              className="px-6 py-2 text-gray-700 bg-gray-200 rounded-md hover:bg-gray-300 transition-colors"
            >
              Reset
            </button>
          )}
          <button
            type="button"
            onClick={handleUpload}
            disabled={!canUpload || isUploading}
            className={`px-6 py-2 rounded-md transition-colors flex items-center gap-2 ${
              canUpload && !isUploading
                ? "text-white bg-add-button hover:bg-indigo-700"
                : "bg-gray-400 text-gray-500 cursor-not-allowed"
            }`}
          >
            {isUploading ? (
              <>
                <div className="w-4 h-4 border-2 border-white border-t-transparent rounded-full animate-spin"></div>
                <span>Uploading...</span>
              </>
            ) : (
              <>
                <Upload size={16} />
                <span>Upload {validRecordsCount > 0 ? `${validRecordsCount} Record(s)` : ""}</span>
              </>
            )}
          </button>
        </div>
      </div>
    </div>
  );
};

export default ArchiveUploadModal;
